#@data/values
---
rolebindings:
- namespace: demo
  create_namespace: true
  tap:
    desired_namespace:
      enabled: true
      params:
        language: java
  users:
  - name: alex
    roles: [ app-developer ]
    clusterroles: [ view ]
  - name: peter
    roles: [ app-developer, app-operator ]
  - name: oliver
    roles: [ app-operator ]
  groups:
  - name: demo-users
    clusterroles: [ view ]
  serviceaccounts:
  - name: ci-bot
    create_serviceaccount: true
    roles: [ app-developer ]
    clusterroles: [ view ]
- namespace: alex
  tap:
    desired_namespace:
      enabled: true
  users:
  - name: alex
    roles: [ app-developer ]
    clusterroles: [ edit ]
  serviceaccounts:
  - name: foo
    create_serviceaccount: true
- namespace: default
  users:
  - name: demo
    clusterroles: [ admin ]

clusterrolebinding:
  users:
  - name: maki
    clusterroles: [ cluster-admin ]
  groups:
  - name: administrators
    clusterroles: [ cluster-admin ]
  - name: users
    clusterroles: [ view ]
  serviceaccounts:
  - name: kapp-bot
    namespace: kapp
    create_serviceaccount: true
    clusterroles: [ admin ]