#@data/values
---
rolebindings:
- namespace: demo
  create_namespace: true
  tap:
    enabled: true
    grype:
      enabled: true
      metadata_store:
        url: https://metadata-store.view.example.com
        caSecret:
          name: store-ca-cert
          importFromNamespace: metadata-store-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: metadata-store-secrets
  users:
  - name: alex
    roles: [ app-developer ]
    clusterroles: [ view ]
  - name: peter
    roles: [ app-developer, app-operator ]
  - name: oliver
    roles: [ app-operator ]
  groups:
  - name: demo-users
    clusterroles: [ view ]
  serviceaccounts:
  - name: ci-bot
    create_serviceaccount: true
    roles: [ app-developer ]
    clusterroles: [ view ]
- namespace: alex
  tap:
    enabled: true
    service_account: foo
  users:
  - name: alex
    roles: [ app-developer ]
    clusterroles: [ edit ]
  serviceaccounts:
  - name: foo
    create_serviceaccount: true
- namespace: default
  users:
  - name: demo
    clusterroles: [ admin ]

clusterrolebinding:
  users:
  - name: maki
    clusterroles: [ cluster-admin ]
  groups:
  - name: administrators
    clusterroles: [ cluster-admin ]
  - name: users
    clusterroles: [ view ]
  serviceaccounts:
  - name: kapp-bot
    namespace: kapp
    create_serviceaccount: true
    clusterroles: [ admin ]