---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: ghcr.io/making/rbac-mgmt-bundle:0.0.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.0.1
          url: ghcr.io/making/rbac-mgmt-bundle:0.0.1
  image: ghcr.io/making/rbac-mgmt-bundle@sha256:cb49882cb692a9f662ad96edef67e4f32c41bbec47065389472ebdb75542fb95
kind: ImagesLock
