#@data/values-schema
---
#@schema/desc "Definition of SecretImport for tap-registry"
tap_registry:
  #@schema/desc "name of the tap-registry secret"
  name: tap-registry
  #@schema/desc "namespace where the tap-registry secret is exported"
  import_from_namespace: tap-install
#@schema/desc "Definition of SecretImport for registry-credentials"
registry_credentials:
  #@schema/desc "name of the registry-credentials secret"
  name: registry-credentials
  #@schema/desc "namespace where the registry-credentials secret is exported"
  import_from_namespace: build-service
#@schema/desc "Definition of RoleBindings per namespace"
rolebindings:
- #@schema/desc "Namespace for the rolebinding"
  namespace: ""
  #@schema/desc "Whether to create the namespace"
  create_namespace: false
  #@schema/desc "Developer Configurations for Tanzu Application Platform per namespace"
  tap:
    #@schema/desc "Configuration for a desired namespace"
    desired_namespace:
      #@schema/desc "Whether it is a desired namespace"
      enabled: false
      #@schema/desc "params for the namespace"
      #@schema/type any=True
      params: { }
    #@schema/desc "Whether to enable developer configurations for Tanzu Application Platform"
    enabled: false
    #@schema/desc "Whether to make kapp forget about TAP related resources"
    orphan: false
    #@schema/desc "service account name"
    service_account: default
    #@schema/desc "Configuration of grype package"
    grype:
      #@schema/desc "Whether to install grype package"
      enabled: false
      #@schema/desc "grype version"
      version: 1.3.0
      #@schema/desc "grype metadata store config"
      #@schema/type any=True
      metadata_store: {}
  #@schema/desc "Definition of RoleBinding for users"
  #@schema/examples ("Example of users", [{"name": "alex@example.com", "roles": ["app-developer"]}, {"name": "oliver@example.com", "roles": ["app-operator"], "clusterroles": ["admin"]}])
  users:
  - #@schema/desc "Username to bind the roles"
    name: ""
    #@schema/desc "Roles to bind to the user"
    roles:
    #@schema/desc "Role name to bind to the user"
    - ""
    #@schema/desc "ClusterRoles to bind to the user"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the user"
    - ""
  #@schema/desc "Definition of RoleBinding for groups"
  #@schema/examples ("Example of groups", [{"name": "developers", "roles": ["app-developer"]}, {"name": "operators", "roles": ["app-operator"], "clusterroles": ["admin"]}])
  groups:
  - #@schema/desc "Group name to bind the roles"
    name: ""
    #@schema/desc "Roles to bind to the group"
    roles:
    #@schema/desc "Role name to bind to the group"
    - ""
    #@schema/desc "ClusterRoles to bind to the group"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the group"
    - ""
  #@schema/desc "Definition of RoleBinding for service accounts"
  #@schema/examples ("Example of serviceaccounts", [{"name": "ci-bot", "clusterroles": ["ci-role"]}])
  serviceaccounts:
  - #@schema/desc "Service account name to bind the roles"
    name: ""
    #@schema/desc "Namespace of the service account"
    #@schema/nullable
    namespace: ""
    #@schema/desc "Whether to create the service account"
    create_serviceaccount: false
    #@schema/desc "Roles to bind to the service account"
    roles:
    #@schema/desc "Role name to bind to the service account"
    - ""
    #@schema/desc "ClusterRoles to bind to the service account"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the service account"
    - ""
#@schema/desc "Definition of ClusterRoleBindings"
clusterrolebinding:
  #@schema/desc "Definition of ClusterRoleBinding for users"
  #@schema/examples ("Example of users", [{"name": "alex@example.com", "clusterroles": ["app-developer"]}, {"name": "oliver@example.com", "clusterroles": ["app-operator"]}])
  users:
  - #@schema/desc "Username to bind the roles"
    name: ""
    #@schema/desc "ClusterRoles to bind to the user"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the user"
    - ""
  #@schema/desc "Definition of ClusterRoleBinding for groups"
  #@schema/examples ("Example of groups", [{"name": "developers", "clusterroles": ["app-developer"]}, {"name": "operators", "clusterroles": ["app-operator"]}])
  groups:
  - #@schema/desc "Group name to bind the roles"
    name: ""
    #@schema/desc "ClusterRoles to bind to the group"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the group"
    - ""
  #@schema/desc "Definition of ClusterRoleBinding for service accounts"
  #@schema/examples ("Example of serviceaccounts", [{"name": "ci-bot", "clusterroles": ["ci-role"]}])
  serviceaccounts:
  - #@schema/desc "Service account name to bind the roles"
    name: ""
    #@schema/desc "Namespace of the service account"
    #@schema/nullable
    namespace: ""
    #@schema/desc "Whether to create the service account"
    create_serviceaccount: false
    #@schema/desc "ClusterRoles to bind to the service account"
    clusterroles:
    #@schema/desc "ClusterRole name to bind to the service account"
    - ""