#@ load("@ytt:data", "data")
#@ rolebinding = data.values.clusterrolebinding if hasattr(data.values, 'clusterrolebinding') else {}
#@ bindings = {}
#@ if hasattr(rolebinding, 'users'):
#@   for user in rolebinding.users:
#@     if hasattr(user, 'clusterroles'):
#@       for role in user.clusterroles:
#@         if bindings.get(role) == None :
#@           bindings[role] = { 'users': {} }
#@         end
#@         bindings[role]['users'].update({ user.name: { 'name': user.name } })
#@       end
#@     end
#@   end
#@ end
#@ if hasattr(rolebinding, 'groups'):
#@   for group in rolebinding.groups:
#@     if hasattr(group, 'clusterroles'):
#@       for role in group.clusterroles:
#@         if bindings.get(role) == None :
#@           bindings[role] = { 'groups': {} }
#@         else:
#@           bindings[role].update({ 'groups': {} })
#@         end
#@         bindings[role]['groups'].update({ group.name: { 'name': group.name } })
#@       end
#@     end
#@   end
#@ end
#@ if hasattr(rolebinding, 'serviceaccounts'):
#@   for serviceaccount in rolebinding.serviceaccounts:
#@     if hasattr(serviceaccount, 'clusterroles'):
#@       for role in serviceaccount.clusterroles:
#@         if bindings.get(role) == None :
#@           bindings[role] = { 'serviceaccounts': {} }
#@         else:
#@           bindings[role].update({ 'serviceaccounts': {} })
#@         end
#@         sa = dict(serviceaccount)
#@         sa.pop('roles', None)
#@         sa.pop('clusterroles', None)
#@         bindings[role]['serviceaccounts'].update({ serviceaccount.name: sa })
#@       end
#@     end
#@   end
#@ end
#@ for role in bindings.keys():
#@   for subject in bindings[role].keys():
#@     bindings[role][subject] = bindings[role][subject].values()
#@   end
#@ end
#@ for role in bindings.keys():
#@   name = role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ "{}-binding".format(name)
  labels:
    rbac-mgmt: "managed"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ name
subjects:
#@   if bindings[role].get('users'):
#@     for user in bindings[role].get('users'):
- kind: User
  name: #@ user.get('name')
#@     end
#@   end
#@   if bindings[role].get('groups'):
#@     for group in bindings[role].get('groups'):
- kind: Group
  name: #@ group.get('name')
#@     end
#@   end
#@   if bindings[role].get('serviceaccounts'):
#@     for serviceaccount in bindings[role].get('serviceaccounts'):
- kind: ServiceAccount
  name: #@ serviceaccount.get('name')
  #@ if/end serviceaccount.get('namespace'):
  namespace: #@ serviceaccount.get('namespace')
#@     end
#@   end
#@ end