#@ load("@ytt:data", "data")
#@ for/end name in [ rolebinding.namespace.lower() for rolebinding in data.values.rolebindings if (hasattr(rolebinding, "create_namespace") and rolebinding.create_namespace) ]:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ name
  labels:
    rbac-mgmt: "managed"